nmstate/nmpolicy

.github/workflows/check.yaml
The golang version at go.mod and github actions id different let's pin
them to 1.16 since it's the version at go.mod.
=> ci, actions: pin to go.mod golang version

.github/workflows/check.yaml, .golangci.yml, cmd/nmpolicy/main.go, docs/_config.yml, nmpolicy/internal/ast/equal.go, nmpolicy/internal/ast/equal_test.go, nmpolicy/internal/ast/types.go, nmpolicy/internal/ast/types_test.go, nmpolicy/internal/ast/values.go, nmpolicy/internal/lexer/token.go, nmpolicy/operations.go, nmpolicy/types.go, scripts/check.sh, scripts/make.sh, tests/basic_test.go
To ensure that the golang code has the proper license header in place
this change add a linter that check that.
The change also add the missing headers and modify the ones that does
not follow the linter.
=> lint, license: Add linter for license header

nmpolicy/internal/resolver/errors.go, nmpolicy/internal/resolver/filter.go, nmpolicy/internal/resolver/path.go, nmpolicy/internal/resolver/resolver.go, nmpolicy/internal/resolver/resolver_test.go, nmpolicy/operations.go, tests/basic_test.go
The PR introduces initial implementation to resolve an AST.
The current implementation supports only "eqfilter" operation as the root of the AST.
Only simple (not regext) strings can be filtered.
This PR is inspired by - https://github.com/nmstate/nmpolicy/pull/4/commits/ee26a0bd9fb784a14e5c9d6ae538ede8455ac890
Depends on https://github.com/nmstate/nmpolicy/pull/20
=> Resolver: resolving "eqfilter" AST filtering a simple string value

nmpolicy/internal/lexer/lexer.go, nmpolicy/internal/parser/parser.go, nmpolicy/operations.go, tests/basic_test.go
Add a test that check that the capture expression
'routes.running.destination="0.0.0.0/0"' capture the expected value and
harcode the lexer/parser/resolver dummies to make it pass.
Also fixed a bug at operations related to meta timestamp.
=> test, integration: Harcoded eq filter test

.github/workflows/check.yaml, .golangci.yml, cmd/nmpolicy/main.go, header.tpl, nmpolicy/internal/ast/equal.go, nmpolicy/internal/ast/equal_test.go, nmpolicy/internal/ast/types.go, nmpolicy/internal/ast/types_test.go, nmpolicy/internal/ast/values.go, nmpolicy/internal/capture/capture.go, nmpolicy/internal/capture/capture_test.go, nmpolicy/internal/lexer/token.go, nmpolicy/internal/parser/parser.go, nmpolicy/internal/resolver/errors.go, nmpolicy/internal/resolver/filter.go, nmpolicy/internal/resolver/path.go, nmpolicy/internal/resolver/resolver.go, nmpolicy/internal/resolver/resolver_test.go, nmpolicy/operations.go, nmpolicy/types/types.go, scripts/make.sh, tests/basic_test.go
The addlincese tool does not do a proper check of headers and does not
allow to enforce a custom time with block comments. This change replace
it with go-header that allow all of this, although we miss the headers
fix.
=> lint, header: Replace addlincese with go-header

nmpolicy/internal/parser/errors.go, nmpolicy/internal/parser/parser.go, nmpolicy/internal/parser/parser_test.go
parser, eqfilter: Generate the operator AST
To implement the filter `routes.running.destination=="0.0.0.0/0"` the
eqfilter token has to be parsed and transformed into an AST, this change
expect something like `token.Identity[, token.Identity|token.Number], token.EQFILTER, token.String` and transform
it into ast.EqFilter{ast.Identity{"currentState"}, ast.Path{"routes",
"running", "destination"}, ast.String{"0.0.0.0/0"}} if the input is not
correct it will return a specific error.
=> parser, path/eqfilter: Implement minimal parser for `routes.runnig.destination="0.0.0.0/0"`

nmpolicy/internal/resolver/errors.go, nmpolicy/internal/resolver/filter.go, nmpolicy/internal/resolver/resolver.go, nmpolicy/internal/resolver/resolver_test.go
Using a error prefix at a recursive function make the final error find
the prefix repeated. This change remove that by adding the prefix at the
recursive function caller, it also compare the error string at tests.
=> resolver, filter: Move out error prefix

nmpolicy/internal/capture/capture_entry.go, nmpolicy/internal/expander/state_expander.go, nmpolicy/internal/expander/state_expander_test.go, nmpolicy/operations.go, tests/basic_test.go
This PR is implementing the state expander. The expander is responsible to substitute the capture references (e.g `{{ capture.primary-nic.interfaces.0.ipv4.dhcp }}`) in the desired state with the resolved captured value.
=> expander: Inserting the captured snippet to the desired state

nmpolicy/internal/parser/parser.go, nmpolicy/internal/parser/parser_test.go
Since the tokens are not passed at the constructor the parser the tokens
member is reset at `Resolve` functions, but the tokens index has to be
reset too. This change reset the Parser at full at `Resolve` function.
=> parser: Allow reuse of the parser

nmpolicy/internal/ast/types.go, nmpolicy/internal/parser/errors.go, nmpolicy/internal/parser/parser.go, nmpolicy/internal/parser/parser_test.go, nmpolicy/internal/resolver/path.go, nmpolicy/internal/resolver/resolver.go, nmpolicy/internal/resolver/resolver_test.go, nmpolicy/internal/resolver/terminal.go, tests/basic_test.go
To continue with the next capture entry `routes.running.next-hop-interface==capture.default-gw.routes.running.0.next-hop-interface` the following features need to be implemented:
- parsing and resolving numeric values to reference a list index.
- understand capture reference on paths like `capture.default-gw` and resolve it if it's not already resolved
- walk the path after a capture entry reference so it returns not state but the value it points to.
=> main scenario: Implement number and capture entry reference

.github/workflows/check.yaml, Makefile
Having a Makefile at top project make easy for new comers and distro
packagers to follow how to build/lint/test the project. This change add
a Makefile wrapping the targets at ./scripts/make.sh.
=> devel: Add Makefile wrapper around make.sh

nmpolicy/internal/capture/capture.go, nmpolicy/internal/capture/capture_entry.go, nmpolicy/internal/capture/capture_entry_test.go, nmpolicy/internal/capture/capture_test.go, nmpolicy/internal/capture/stubs_test.go, nmpolicy/internal/lexer/lexer.go, nmpolicy/internal/parser/parser.go, nmpolicy/internal/parser/parser_test.go, nmpolicy/internal/resolver/resolver.go, nmpolicy/internal/resolver/resolver_test.go, nmpolicy/operations.go, nmpolicy/types/typestest/typestest.go, tests/basic_test.go
The ResolveCaptureEntryPath implementation is empty, this PR do the
wiring to connect `CaptureEntry` to lexer, parser and resolver. It also
extend the test stubs so the output is syntetized from the inputs.
After merging this we have to create some issues with the following tech debt:
- The `capturedStates` YAMLs are unmarshaled multiple times since we are passing marshaled version to the resolver
- The `CaptureEntry` has to be renamed to `EntryPathResolver` so we can do `captureEntryPathResolver := capture.EntryPathResolver` and then we use it like `captureEntryPath.Resolve(...)`
- The `Capture` has to be renamed as `Resolver` so we can do `captureResolver := capture.Resolver` and then `captureResolver.Resolve(...)`.
=> capture: Wire up ResolveCaptureEntryPath

cmd/nmpolicy/main.go
To compile the nmpolicy library when we compile the cli this change
import nmpolicy and do dummy call to GenerateState.
=> cli: Import nmpolicy into cmd

cmd/nmpolicy/main.go, nmpolicy/internal/capture/capture.go, nmpolicy/internal/capture/capture_entry.go, nmpolicy/internal/capture/capture_entry_test.go, nmpolicy/internal/capture/capture_test.go, nmpolicy/internal/capture/stubs_test.go, nmpolicy/internal/expander/state_expander.go, nmpolicy/internal/expander/state_expander_test.go, nmpolicy/internal/operations.go, nmpolicy/internal/resolver/resolver.go, nmpolicy/internal/resolver/resolver_test.go, nmpolicy/internal/types/types.go, nmpolicy/internal/types/typestest/typestest.go, nmpolicy/operations.go, tests/basic_test.go
Current implementation do a lot of marshaling/unmarshaling from yaml at different levels of the code mixing it with the logic, this change make internal package agnostico to YAML/JSON format by using the unmarshaled version of it represented by some internal types.
The PR has being splited into different commits to make review easier but they are not suppose to pass "make".
=> [tech debt] internal, types: Use unmarshaled structs at the internal package.

.gitignore, .goreleaser.yml
The project will need to release also some binaries for the cli, this
change add a goreleaser mechanism to release nmpolicy with nice
changelog to github.
=> infra: Add a goreleaser mechanism

.github/release.yml
It will add some categories on the release notes depending on the PRs
labels.
=> infra: Add github release notes template

nmpolicy/internal/parser/parser.go, nmpolicy/internal/parser/parser_test.go
If a user pass an empty expression parser do an illegal access to the
tokens list, this change add a test and a fix to mimic this scenario.
=> parser: Return empty if there is no tokens

.github/workflows/check.yaml
All the commits need to complai with Signed-Off-By. This change add a
github action to enforce it.
=> infra: Add DCO checker

nmpolicy/internal/parser/parser.go, nmpolicy/internal/parser/parser_test.go
When the expressin is empty the lexer will return a slice of tokens with
just one EOF, there is a bug at parser that throws a panic trying to
access the last token. This change add the guard to prevent that.
/kind bug
/area lib
=> parser: Don't panic on single eof token

nmpolicy/internal/ast/types.go, nmpolicy/internal/parser/errors.go, nmpolicy/internal/parser/parser.go, nmpolicy/internal/parser/parser_test.go, nmpolicy/internal/resolver/errors.go, nmpolicy/internal/resolver/filter.go, nmpolicy/internal/resolver/path.go, nmpolicy/internal/resolver/replace.go, nmpolicy/internal/resolver/resolver.go, nmpolicy/internal/resolver/resolver_test.go
For the main scenario NMPolicy need to resolve `capture.base-iface-routes | routes.running.next-hop-interface:="br1"` part of this expression is the replace operator `:=` this PR implement that operator at parser and resolver and also allow filter/replace to use a capture ref path as input so next PR implementing the pipe will involve only the parser.
Thech debt:
- For apply functions at `nmpolicy/internal/path.go`:
- Use a struct so func and flags does not need to be passed around
- The expectedNode argument is not needed to be passed if we function to apply is a closure containing it.
=> parser, resolver: Implement Replace operator :=

nmpolicy/internal/lexer/token.go, nmpolicy/internal/parser/errors.go, nmpolicy/internal/parser/parser.go, nmpolicy/internal/parser/parser_test.go, tests/basic_test.go
For the main scenario we have an expression like [1] this expression
uses a capture reference path as pipe in and a replace expression as
pipe out. This change convert pipe as the first argument on the ternary
replace operation.
[1] capture.base-iface-routes | routes.running.next-hop-interface:="br1"
=>  resolver: Implement pipe with capture and replace

nmpolicy/internal/resolver/filter.go, nmpolicy/internal/resolver/resolver_test.go
A field like "description" can be missing at some interfaces,                   
this make eqfilter to fail since it expected the the field is present.          
This change does not fail if the path does not exist, instead it just           
filters out the entry.      
Closes: https://github.com/nmstate/nmpolicy/issues/74
=> resolver, eqfilter: Support optional fields

nmpolicy/internal/capture/capture.go, nmpolicy/internal/capture/capture_entry.go, nmpolicy/internal/capture/stubs_test.go, nmpolicy/internal/expression/error.go, nmpolicy/internal/expression/error_test.go, nmpolicy/internal/expression/snippet.go, nmpolicy/internal/expression/snippet_test.go, nmpolicy/internal/lexer/lexer.go, nmpolicy/internal/lexer/lexer_test.go, nmpolicy/internal/parser/parser.go, nmpolicy/internal/parser/parser_test.go, nmpolicy/internal/resolver/resolver.go, nmpolicy/internal/resolver/resolver_test.go, nmpolicy/internal/types/typestest/typestest.go, tests/basic_test.go
At lexer, parser is easy to detect the rune, token that is generating
the error. This change wrap those errors with the expression and a
pointer.
Since the parser knows only about tokens, this change add also the
expression to the parser so it can use it to wrap the errors.
At resolver the ast.Node contains a Position field that points to the expressions
rune where the ast.Node was generated from. This change use that
position to to wrap the errors with a snippet that contains the
expression and a pointer to the place that generated the error.
To acomplish that the capture expressions are passed to the resolver so
it can search for the expression string to create the snippet.
The snippet pointer marks until operators but not inside the paths, this
can be fixed at a follow up.
The errors …
=> lexer, parser: Decorate errors with expression snippet.

nmpolicy/internal/parser/errors.go, nmpolicy/internal/parser/parser.go, nmpolicy/internal/parser/parser_test.go, nmpolicy/internal/resolver/resolver_test.go
One of the feature is replacing with the captured state from a capture
entry path. This change add support for it at the parser and create a
unit test for the resolver since resolver has the feature already.
=> replace, test: Add unit test to replace with cap

nmpolicy/internal/ast/equal.go, nmpolicy/internal/ast/equal_test.go, nmpolicy/internal/ast/types.go, nmpolicy/internal/ast/types_test.go, nmpolicy/internal/capture/stubs_test.go, nmpolicy/internal/parser/parser.go, nmpolicy/internal/resolver/resolver.go, tests/basic_test.go
As part of the effort to improve the error messages, AST node is now a stringer.
=> Make the AST node a stringer

nmpolicy/internal/resolver/errors.go, nmpolicy/internal/resolver/filter.go, nmpolicy/internal/resolver/path.go, nmpolicy/internal/resolver/replace.go, nmpolicy/internal/resolver/resolver.go, nmpolicy/internal/resolver/resolver_test.go, tests/basic_test.go
The PR contains 3 commits-
1. Place snippet marker on correct part of a Ternary operation
2. Place snippet marker on correct key of a path
3. Support optional keys on any part of the path (continues PR #75, which allowed optional keys on the last key of the path).
=> Resolver: Place snippet marker more accuratly

docs/Makefile
To prevent github from running jekyll on the already generated page a
.jekyll have has to be added.
https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#troubleshooting-publishing-problems-with-your-github-pages-site
=> docs: Add .nojekyll build marker

docs/examples/all-linux-bridges-down/captured.yaml, docs/examples/bridge-on-default-gw-dhcp/captured.yaml, docs/examples/bridge-on-default-gw-no-dhcp/captured.yaml, docs/examples/ovs-slb-bond-primary-secondary/captured.yaml, nmpolicy/internal/operations.go, nmpolicy/internal/types/types.go, nmpolicy/operations.go, nmpolicy/types/types.go, tests/basic_test.go
The MetaInfo version is really needed at captured states. This change
move the version there.
=> types: Remove main MetaInfo

nmpolicy/internal/resolver/filter.go, nmpolicy/internal/resolver/path.go, nmpolicy/internal/resolver/replace.go, nmpolicy/internal/resolver/resolver.go, nmpolicy/internal/resolver/resolver_test.go, nmpolicy/internal/resolver/visitor.go, nmpolicy/internal/resolver/walk.go
The code that resolves resolve and filter is mixed up at `path.go` so for example the `replace` does not need the `shouldFilter` feature but still the code that runs it has to understand it.
This PR do the following:
- Encapsulate the path advancing into the function `nextStep` and `hasMoreSteps`
- Use a map to decide at what part of the path we should filter entries.
- Create a pair of callbacks for visit a map with an identity and visit a slice when there is no index in the path
- Move the code from filter/replace to their correct place at filter.go and replace.go, implementing previous callbacks.
- Replace the "Fn" visit functions with a `stateVisitor` interface
- Implement path walk using a `pathVisitor`
Closes  https://github.com/nmstate/nmpolicy/issues/83
=> resolver: Refactor visitor pattern

docs/examples/convert-dhcp-to-static/captured.yaml, docs/examples/convert-dhcp-to-static/current.yaml, docs/examples/convert-dhcp-to-static/generated.yaml, docs/examples/convert-dhcp-to-static/policy.md, docs/user-guide/102-policy-syntax.md, nmpolicy/internal/resolver/filter.go, nmpolicy/internal/resolver/resolver.go, nmpolicy/internal/resolver/resolver_test.go
Sometime is needed for a capture to reference just a part of current
state without comparing any value. This change add the possibility to
pass a path to a capture and return a Nmstate with data at that path.
This allow policies like the following:
```yaml
capture:
eth1-iface: interfaces.name == "eth1"
eth1-routes: routes.running.next-hop-interface == "eth1"
dns: dns-resolver.running
desiredState:
interfaces:
- name: eth1
type: ethernet
state: up
ipv4:
address: "{{ capture.eth1-iface.interfaces.0.ipv4.address }}"
dhcp: false
enabled: true
routes:
config: "{{ capture.eth1-routes.running }}"
dns-resolver:
config: "{{ capture.dns.dns-resolver.running }}"
```
Signed-off-by: Enrique Llorente <ellorent@redhat.com>
=> resolver: Filter current state by path

docs/user-guide/102-policy-syntax.md
The path filter contains problematic syntax on the docs.
Signed-off-by: Enrique Llorente <ellorent@redhat.com>
=> docs: Fix path filter docs

docs/examples/all-ethernet-up/captured.yaml, docs/examples/all-ethernet-up/current.yaml, docs/examples/all-ethernet-up/generated.yaml, docs/examples/all-ethernet-up/policy.md, nmpolicy/internal/resolver/replace.go, nmpolicy/internal/resolver/resolver_test.go, tests/examples_test.go
When the replace expression is referencing a missing path nmpolicy was failing since it cannot find the keys in the state. This PR create new empty dictionaries to fill in the gaps from the replace expression.
=> replace: Return map if missing path
